import './globals.css';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import { ThemeModeScript } from 'flowbite-react';

import { NavBar } from '@/components/navbar';
import { SideBar } from '@/components/sidebar';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={manrope.className}>
        <SideBar />
        <main className="lg:ml-64 h-screen">
          <NavBar />
          <div className="px-5 py-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
